/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    container: {
      center: true,
    },
    colors: {
      blue: '#007bff',
      indigo: '#6610f2',
      purple: '#6f42c1',
      lightPurple: '#564FFF',
      Pink: '#e83e8c',
      red: '#ff564f',
      orange: '#fd7e14',
      yellow: '#ffc107',
      green: '#28a745',
      teal: '#20c997',
      cyan: '#17a2b8',
      whit: '#fff',
      gray: '#6c757d',
      grayDark: '#343a40',
      primary: '#007bff',
      secondary: '#6c757d',
      success: '#28a745',
      info: '#17a2b8',
      warning: '#ffc107',
      danger: '#dc3545',
      light: '#f8f9fa',
      dark: '#343a40',
      transparent: 'transparent',
      white: "#fff",
      black: "#383838",
      bgColor: "#33415C"
    },
    content: {
      kidsStar: "url('./src/assets/Image/kid2.star.svg')",
      triangle: "url('./src/assets/Image/triangle.svg')",
      bgCircleColor: "url('./src/assets/Image/kids-Color-Circle.svg')",
      bgCircle: "url('./src/assets/Image/kids-bg-circle.svg')",
      dotsSquare: "url('./src/assets/Image/dots-square.svg')",
      halfCircle: "url('./src/assets/Image/HalfCircle.svg')",
      csc: "url('./src/assets/Image/csc.svg')",
      familyPic: "url('./src/assets/Image/familyPic.svg')",
      subscribeLeft: "url('./src/assets/Image/subscribeLeft.svg')",
      subscribeRight: "url('./src/assets/Image/subscribeRight.svg')",
      teacherKid1: "url('./src/assets/Image/teacher_kid1.png')",
      teacherKid2: "url('./src/assets/Image/teacher_kid2.png')",
    },
    screens: {
      xs: "480px",
      sm: "768px",
      md: "1060px",
    },
  },
  plugins: [],
}